Name:           ros-melodic-rail-segmentation
Version:        0.1.15
Release:        1%{?dist}
Summary:        ROS rail_segmentation package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/rail_segmentation
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-devel
Requires:       boost-python2-devel
Requires:       boost-python3-devel
Requires:       ros-melodic-message-runtime
Requires:       ros-melodic-pcl-conversions
Requires:       ros-melodic-pcl-ros
Requires:       ros-melodic-rail-manipulation-msgs
Requires:       ros-melodic-roscpp
Requires:       ros-melodic-roslib
Requires:       ros-melodic-sensor-msgs
Requires:       ros-melodic-std-srvs
Requires:       ros-melodic-tf
Requires:       ros-melodic-tf2
Requires:       ros-melodic-tf2-ros
Requires:       yaml-cpp-devel
BuildRequires:  boost-devel
BuildRequires:  boost-python2-devel
BuildRequires:  boost-python3-devel
BuildRequires:  pkgconfig
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-message-generation
BuildRequires:  ros-melodic-pcl-conversions
BuildRequires:  ros-melodic-pcl-ros
BuildRequires:  ros-melodic-rail-manipulation-msgs
BuildRequires:  ros-melodic-roscpp
BuildRequires:  ros-melodic-roslib
BuildRequires:  ros-melodic-sensor-msgs
BuildRequires:  ros-melodic-std-srvs
BuildRequires:  ros-melodic-tf
BuildRequires:  ros-melodic-tf2
BuildRequires:  ros-melodic-tf2-ros
BuildRequires:  yaml-cpp-devel

%description
Segmentation Functionality from the RAIL Lab

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Fri Jun 28 2019 Russell Toris <russell.toris@gmail.com> - 0.1.15-1
- Autogenerated by Bloom

* Thu Jun 27 2019 Russell Toris <russell.toris@gmail.com> - 0.1.14-1
- Autogenerated by Bloom

* Fri Jun 07 2019 Russell Toris <russell.toris@gmail.com> - 0.1.13-1
- Autogenerated by Bloom

